before:
  hooks:
    - go mod tidy
builds:
  - binary: devx
    main: "./cmd/devx"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "darwin" }}Darwin
      {{- else if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "windows" }}Windows
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - homepage: "https://devx.guku.io/"
    tap:
      owner: devopzilla
      name: homebrew-guku-devx
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
dockers:
  - image_templates:
      - "ghcr.io/devopzilla/guku-devx:latest"
      - "ghcr.io/devopzilla/guku-devx:{{ .Tag }}"
      - "ghcr.io/devopzilla/guku-devx:v{{ .Major }}.{{ .Minor }}"
